// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:4ab26a4c-7f2d-4f8d-af6b-f3ca14b40856",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_xVyNwpxRf",
    "aws_user_pools_web_client_id": "4vsmtro6gahfrfvmu9kg6i9t0e",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jgvcqjibfvfjhb7jw7jchlgyf4.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fysiopzpbfefhod2jl5m6krlea"
};


export default awsmobile;
